// Code generated by "stringer -type=FileKind"; DO NOT EDIT.

package parse

import "fmt"

const _FileKind_name = "ImageArchiveAudioVideoBinaryExecutableDocumentFontWindowsResourceMacOSResource"

var _FileKind_index = [...]uint8{0, 5, 12, 22, 28, 38, 46, 50, 65, 78}

func (i FileKind) String() string {
	i -= 1
	if i < 0 || i >= FileKind(len(_FileKind_index)-1) {
		return fmt.Sprintf("FileKind(%d)", i+1)
	}
	return _FileKind_name[_FileKind_index[i]:_FileKind_index[i+1]]
}
